# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
    node: circleci/node@5.0.0
defaults: &defaults
    parallelism: 1
    working_directory: ~/repo
    docker:
        - image: cimg/node:16.19.0
release: &release
    steps:
        - checkout
        - attach_workspace:
              at: ~/repo
        - run:
              name: Release npm package
              command: npx semantic-release

jobs:
    setup:
        <<: *defaults
        steps:
            - checkout
            # Download and cache dependencies
            - node/install-packages:
                  pkg-manager: yarn
            - persist_to_workspace:
                  root: ~/repo
                  paths:
                      - node_modules

    check_commit_message:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Define environment variable with lastest commit's message
                  command: |
                      echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
                      source $BASH_ENV
            - run:
                  name: Lint commit message
                  command: echo "$COMMIT_MESSAGE" | npx commitlint

    check_code:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Lint & check
                  command: yarn lint

    build:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Build distributables
                  command: yarn build
            - persist_to_workspace:
                  root: ~/repo
                  paths:
                      - commons/**/dist
                      - components/**/dist

    dry_release:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Dry release
                  command: yarn release:dry

    release:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Release to github packages
                  command: yarn release

workflows:
    check_and_release_workflow:
        jobs:
            - setup
            - check_commit_message:
                  requires:
                      - setup
            - check_code:
                  requires:
                      - check_commit_message
            - build:
                  requires:
                      - check_code
            - dry_release:
                  context: npm-deploy
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
                              - next
            - approve_release:
                  type: approval
                  requires:
                      - dry_release
                  filters:
                      branches:
                          only:
                              - master
                              - next
            - release:
                  context: npm-deploy
                  requires:
                      - approve_release
                  filters:
                      branches:
                          only:
                              - master
                              - next
